Blog Api - Frontend
coder1033/blog-api pull request #2
Opened 2021-03-19 14:31 UTC by coder1033

# Description
- Frontend part of Blog Api project.
- Total 11 routes are there.

# Screenshots
## All posts - /posts
![Screenshot (163)](https://user-images.githubusercontent.com/40430894/111791390-284fad80-88e9-11eb-9a90-cef143dde15c.png)

## Single post - /posts/:id
![Screenshot (167)](https://user-images.githubusercontent.com/40430894/111792010-d196a380-88e9-11eb-8c9f-cdf392af0a6c.png)

## User Signup - /sign-up
### Empty State
![Screenshot (172)](https://user-images.githubusercontent.com/40430894/111793352-3272ab80-88eb-11eb-9c3c-1a5d1ab306ff.png)

### Error State
![Screenshot (173)](https://user-images.githubusercontent.com/40430894/111793389-3bfc1380-88eb-11eb-89be-38503c41e8aa.png)

### Success State
![Screenshot (174)](https://user-images.githubusercontent.com/40430894/111793412-428a8b00-88eb-11eb-9762-22bcecd7dbbe.png)

## User Login - /log-in
### Empty state
![Screenshot (168)](https://user-images.githubusercontent.com/40430894/111792368-30f4b380-88ea-11eb-833f-73ae4d55ba9a.png)

### Error state
![Screenshot (170)](https://user-images.githubusercontent.com/40430894/111792523-584b8080-88ea-11eb-8ba6-7e18b055df7d.png)

### Success state
![Screenshot (171)](https://user-images.githubusercontent.com/40430894/111792707-8335d480-88ea-11eb-95bf-907b18e51593.png)

## Admin Signup - /admin/sign-up
### Empty State
![Screenshot (175)](https://user-images.githubusercontent.com/40430894/111793934-c2185a00-88eb-11eb-93af-4f08bfab86a9.png)

### Error State
![Screenshot (176)](https://user-images.githubusercontent.com/40430894/111794045-d9efde00-88eb-11eb-89cc-e2858e2d7a30.png)

### Success State
![Screenshot (177)](https://user-images.githubusercontent.com/40430894/111794095-e3794600-88eb-11eb-82dc-cd8381dd0e1d.png)

## Single post for admin - /posts/:id
![Screenshot (166)](https://user-images.githubusercontent.com/40430894/111792050-d8251b00-88e9-11eb-8fcb-8346791da7d9.png)

## Create Post - /admin/create-post
### Empty State
![Screenshot (178)](https://user-images.githubusercontent.com/40430894/111794552-584c8000-88ec-11eb-8f69-2593942505b5.png)

### Error State
![Screenshot (179)](https://user-images.githubusercontent.com/40430894/111794634-6ef2d700-88ec-11eb-891e-8e5e1d7b57a8.png)

### Success State
![Screenshot (180)](https://user-images.githubusercontent.com/40430894/111794778-95b10d80-88ec-11eb-9eef-595d373ad3e5.png)

# Tests
## Automated test cases
- None

## Manual test cases
- Checks all the endpoints.
- Creates sample data.
- Checks for validation on each field.

## Browser tested
- [x] Chrome
- [x] Edge
- [x] Opera

# Platform Dependencies
- None

2021-03-22 11:18 UTC, bbbneo333 requested changes

2021-03-22 11:18 UTC, bbbneo333 commented
@coder1033 - You should be actually creating a separate branch for feature specific development and then merge them into develop / master. Please consult to the development guide in the engineering handbook - https://github.com/jalantechnologies/handbook/blob/main/engineering.md#software-development-process.

2021-03-22 11:57 UTC, coder1033 commented on blog-api-frontend/src/api/api.js
> +    localStorage.setItem(
I was testing different ways for that. I'll fix it.
Also in which way, I should use it?

2021-03-23 05:42 UTC, bbbneo333 approved these changes

2021-03-23 05:51 UTC, merged